//! Byte-for-byte port of desktop/observer.mjs canonicalJson(). Do not diverge —
//! any mismatch splits canonical reality between Node and native nodes.

use serde_json::Value;

pub fn canonical_json(value: &Value) -> String {
    match value {
        Value::Null => "null".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => serde_json::to_string(s).expect("string serialization cannot fail"),
        Value::Array(items) => {
            let parts: Vec<String> = items.iter().map(canonical_json).collect();
            format!("[{}]", parts.join(","))
        }
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            let parts: Vec<String> = keys
                .iter()
                .map(|k| {
                    let key_json = serde_json::to_string(k).expect("key serialization cannot fail");
                    format!("{}:{}", key_json, canonical_json(&map[*k]))
                })
                .collect();
            format!("{{{}}}", parts.join(","))
        }
    }
}

#[cfg(test)]
mod golden_vector_tests {
    //! Vectors generated by actually running desktop/observer.mjs's canonicalJson()
    //! + sha256() on 2026-08-21 (see docs/android-foundation/03-NATIVE-CORE-BOUNDARY.md
    //! "Kabul kriteri"). This is the cross-language proof that the native core has NOT
    //! invented a new hashing/identity semantic.

    use super::canonical_json;
    use crate::hashing::sha256_hex;
    use serde_json::{json, Value};

    struct Vector {
        name: &'static str,
        input: Value,
        expected_canonical: &'static str,
        expected_sha256: &'static str,
    }

    fn vectors() -> Vec<Vector> {
        vec![
            Vector { name: "empty_object", input: json!({}), expected_canonical: "{}", expected_sha256: "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a" },
            Vector { name: "sorted_ab", input: json!({"a":1,"b":2}), expected_canonical: "{\"a\":1,\"b\":2}", expected_sha256: "43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777" },
            Vector { name: "unsorted_ba", input: json!({"b":2,"a":1}), expected_canonical: "{\"a\":1,\"b\":2}", expected_sha256: "43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777" },
            Vector { name: "node_identity_payload", input: json!({"agent_name":"test-agent","agent_version":"1.0.0","arch":"arm64","endpoint":"http://127.0.0.1:9300","platform":"android"}), expected_canonical: "{\"agent_name\":\"test-agent\",\"agent_version\":\"1.0.0\",\"arch\":\"arm64\",\"endpoint\":\"http://127.0.0.1:9300\",\"platform\":\"android\"}", expected_sha256: "e063da3fd0d8a02f3bcc981f02eb8a51b83800b15f90abb079cd82695d8c3331" },
            Vector { name: "nested", input: json!({"nested":{"z":1,"a":[1,2,3]},"list":["x","y"]}), expected_canonical: "{\"list\":[\"x\",\"y\"],\"nested\":{\"a\":[1,2,3],\"z\":1}}", expected_sha256: "52e16e3a265845e38f60d3fb7e3771c741d9555379a16a72ade79a62a487bf97" },
            Vector { name: "null_value", input: json!(null), expected_canonical: "null", expected_sha256: "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b" },
            Vector { name: "plain_string", input: json!("plain-string"), expected_canonical: "\"plain-string\"", expected_sha256: "69a35681d46c434bb666f849e810ab79aece20eb130665d6fdf0d9b433c8b842" },
            Vector { name: "number", input: json!(42), expected_canonical: "42", expected_sha256: "73475cb40a568e8da8a045ced110137e159f890ac4da883b6b17dc651b3a8049" },
            Vector { name: "bool_true", input: json!(true), expected_canonical: "true", expected_sha256: "b5bea41b6c623f7c09f1bf24dcae58ebab3c0cdd90ad966bc43a45b44867e12b" },
            Vector { name: "empty_array", input: json!([]), expected_canonical: "[]", expected_sha256: "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945" },
        ]
    }

    #[test]
    fn canonical_json_matches_node_reference() {
        for v in vectors() {
            let got = canonical_json(&v.input);
            assert_eq!(got, v.expected_canonical, "canonical mismatch for vector '{}'", v.name);
        }
    }

    #[test]
    fn sha256_of_canonical_matches_node_reference() {
        for v in vectors() {
            let canonical = canonical_json(&v.input);
            let got = sha256_hex(canonical.as_bytes());
            assert_eq!(got, v.expected_sha256, "sha256 mismatch for vector '{}'", v.name);
        }
    }
}
